### ISSUE TITLE
Anomalous Concept Path for 5A09457

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#13]
**Overview**
In the ACT_COVID ontology, there is a concept with an anomalous path.  This is ICD-10 Procedure 5A09457.  See the attached image where the concept is missing from the parent folder.

**Image**
![5A09457_MissingFromOntologyTree](https://user-images.githubusercontent.com/17863357/80265146-66960b80-864b-11ea-8a13-5dde7a5972dc.png)

**Risk**
Matching observation facts will be counted when the overall "mechanical ventilation" folder is queried, but not when the 5A094 folder or subfolder are queried.

**Analysis**
My analysis is that the concept path is anomalous.  The path is currently: 
`\ACT\UMLS_C0031437\SNOMED_3947185011\UMLS_C0242656\UML_C1444343\UMLS_C0199470\A28335107\A16738804\`

**Suggested Resolution**
I believe the path ought to be: 
`\ACT\UMLS_C0031437\SNOMED_3947185011\UMLS_C0242656\UML_C1444343\UMLS_C0199470\A28322331\A28335107\A16738804\`

I believe that the token `A28322331` is missing from the current path.

Kind regards,  Mark Abajian

**Comment by mim18** [comment]
fixed in V3
