### ISSUE TITLE
Version Number in COVID Ontology Tree

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#15]
Just a suggestion that we maintain a version number in the COVID-19 ontology tree, like we do for the other ontology domains in ACT.

I have an example here that I have added to our copy of the ontology (metadata and shrine_ont) in SQL Server.  Please see attached.

[ACT_COVID_Insert_Version_20200428ma.sql.txt](https://github.com/shyamvis/covid-phenotyping/files/4550054/ACT_COVID_Insert_Version_20200428ma.sql.txt)

I imagine that this code is database-agnostic, but your mileage may vary.

**Comment by mim18** [comment]
good idea
