### ISSUE TITLE
Medications: NDC codes expected?

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#19]
In the Medications tree, most of the leaves have a number of NDC-coded leaves below them.  These are "LI " inactive leaves.

Some medications (for instance, Chloroquine Sulfate) do not have these inactive leaves.  Should we be expecting the NDC leaves for every medication?  Or, not necessarily?  Thank you.

**Comment by mim18** [comment]
only if they exist - not all leaves have NDCs
