### ISSUE TITLE
Folders Missing Codes?

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#23]
The following folders do not appear to have any codes associated with them.  But other folders at their level in the hierarchy seem to have either UMLS or SNOMED codes.  Could these four folders be missing codes?

1. Confirmed Case
2. SARS-CoV-2 Antibodies
3. SARS-CoV-2 nucleic acids (Respiratory)
4. SARS-CoV-2 nucleic acids (Unspecified)

Thank you.

**Comment by mim18** [comment]
no its not necessary. some folders had them to be used as derived facts placeholders
