### ISSUE TITLE
Tooltips Suggestion

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#24]
Tooltips:  Huge, huge, huge improvement in Version 3.  Thank you!

Suggestion:  These two concepts do not have their ICD10 codes displayed in their tooltips, even though other concepts in their same folder do have the ICD10 codes displayed in their tooltips.  Add the ICD10 code to the tooltip for these?

- B97.21
- Z20.828

Thank you.

**Comment by mim18** [comment]
i trunk c_name at 75 to bbuild tool tip. changing to 100
