### ISSUE TITLE
Overuse of "Derived" Token?

### ISSUE THREAD

**Issue by markabajian** [shyamvis/covid-phenotyping#25]
I understand the need to indicate which concepts are being coded as "Derived" facts.  I do not dispute that.

There may be some confusion because the folders that contain the derived facts also contain facts that are not "derived", but are actually coded directly in the patient record.  And when the tooltip for the folder says "derived", the user may believe that **_all the concepts_** that appear in the folder are derived, not just some of them.

These eight folders mention (Derived) in the tooltip, and that may be misleading if these folders contain both derived and "real" facts:

1. Ambulatory
2. Emergency
3. Inpatient (Critical Care)
4. Inpatient (Routine)
5. ECMO
6. Intubation
7. mechanical ventilation
8. supplemental oxygen

Also, the concept_path, c_dimcode, and c_fullname for these folders may use the term Derived, but I have not checked that; or, that may be a lower priority, if the user will never see those.

**Comment by mim18** [comment]
changed
