### ISSUE TITLE
Medications -Empty folders 

### ISSUE THREAD

**Issue by MAS609** [shyamvis/covid-phenotyping#34]
1. Bronchodilators,Sympathomimetic,Inhalation - Its children like Albuterol, Arformoterol,....................., Salmeterol, Terbutaline (ACT Medications VA Classes/Respiratory Tract Medications/Bronchodilators,Sympathomimetic,Inhalation) to be added.
2. Antirheumatics,Other/Sarilumab Auto-Injector &
    Antirheumatics,Other/Sarilumab Prefilled Syringe  ---- child nodes to be added.
3. 'Hormones/Sythetics/Modifiers'/ Epoprostenol
    'Hormones/Sythetics/Modifiers'/ Vasopressin (Usp) --- child nodes to be added.
3 (b) There is also a Typo: Sythetics ---> Synthetics.

**Comment by MAS609** [comment]
Bronchodilators,Sympathomimetic,Inhalation:
Only Epinephrine is included. It has other commonly used drugs like Albuterol, Salmeterol also.

**Comment by mim18** [comment]
shyam - should we add albuterol etc - epinephrine was the only med on the 4CE list
