### ISSUE TITLE
Why ATC codes?

### ISSUE THREAD

**Issue by MAS609** [shyamvis/covid-phenotyping#35]
The following drugs/combinations have RxNorm codes also. But they are coded in ATC in the tree.
Under Loop  Diuretics:
1. Bumetanide and Potassium - RXCUI = 392534
2. Furosemide and Potassium - RXCUI = 392464
3. Ethacrynic acid - RXCUI = 4109 (It has a Typo too - 'Etacrynic Acid (ATC:C03CC01)' ---> 'Ethacrynic acid'
4. Pyretanide - RXCUI = 33770

Under Anti-Malarial:
1. Chloroquine (ATC:P01BA01)
2. Hydroxychloroquine (ATC:P01BA02) - have Chloroquine/HCQ with RXNorm codes at the next level hierarchy. Do we need this ATC and we can have one H_LEVEL less if we get rid of this ATC code?

**Comment by mim18** [comment]
the top ones were not in our ontology yet and i didn't want to put them in before they were in the main med trees.
the last two originally I was trying to be consistent since severely of the treatment drugs only had ATCSs
