### ISSUE TITLE
Lab test values harmonized terms

### ISSUE THREAD

**Issue by shyamvis** [shyamvis/covid-phenotyping#39]
Based on ACT meeting on 5/26/2020 we want to separate the nuclei acids and the antibodies test values.

Rename harmonized values for nucleic acid test as follows:
ANY Equivocal Lab Test -> ANY Equivocal Lab Test (Nucleic Acids)
ANY Negative Lab Test -> ANY Negative Lab Test (Nucleic Acids) 
ANY Pending Lab Test -> ANY Pending Lab Test (Nucleic Acids) 
ANY Positive Lab Test -> ANY Positive Lab Test (Nucleic Acids)

Create new harmonized values for antibody tests as follows:
ANY Equivocal Lab Test (Antibodies)
ANY Negative Lab Test (Antibodies) 
ANY Pending Lab Test (Antibodies) 
ANY Positive Lab Test (Antibodies)

Minor name changes:
SARS-CoV-2 nucleic acids (Respiratory specimen) -> SARS-CoV-2 Nucleic Acids (Respiratory specimen)  [capitalize nucleic acids]  
SARS-CoV-2 nucleic acids (Unspecified specimen) -> SARS-CoV-2 Nucleic Acids (Unspecified specimen)  [capitalize nucleic acids]

**Comment by mim18** [comment]
all nucleic acid tests are Equivocal?

**Comment by shyamvis** [comment]
Fixed.

**Comment by shyamvis** [comment]
LOINC value sets:

Nucleic Acids (oral fluids): Positive, Negative, Equivocal https://loinc.org/LL2009-0/
Nucleic Acids (serum or plasma): Detected, Not detected, Equivocal, Inconclusive https://loinc.org/LL956-4/
