### ISSUE TITLE
Illness severity concepts update

### ISSUE THREAD

**Issue by shyamvis** [shyamvis/covid-phenotyping#40]
Based on ACT meeting on 5/26/2020 we want to specify that the moderate and severe illness concepts are specific to the respiratory system which is the commonest presentation in Covid. In future, this will allow us to add moderate and severe illness concepts for other systems e.g. renal, neurological. 

Changes:
Illness Severity -> Illness Severity (Respiratory)
   Moderate Illness -> Moderate Illness (Respiratory)
        Moderate Illness (Derived) -> Moderate Illness (Respiratory) (Derived)
   Severe Illness -> Severe Illness (Respiratory)
        Severe Illness (Derived) -> Severe Illness (Respiratory) (Derived)

**Comment by mim18** [comment]
where would that leave ECMO and SIRS aren't those multi-organ/system failures?

**Comment by MAS609** [comment]
Yes, SIRS - MOF.
 Initiation of ECMO could be prompted by either Respiratory failure/Cardiogenic shock/Septic shock.  Can  we add another concept like Severe Illness (Multiple Systems)?

**Comment by MAS609** [comment]
Can we add another concept like "Severe Illness (Multiple Systems)?
